/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ultetes;

import java.beans.XMLDecoder;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author solya
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    private List<JLabel> labelek = new ArrayList<JLabel>();
    private List<Resztvevo> vendegek = new ArrayList<>();
    private List<Szolgaltato> szolgaltatok = new ArrayList<>();
    private List<Szek> szekek = new ArrayList<>();
    private Integer szekSzam = -1;
    
    
    /*String balSzek = "balSzek";
    String jobbSzek = "jobbSzek";
    JLabel ideiglenes = new JLabel();*/
    
    public Form() {
        initComponents();
        
        VendegVagyokBtn.setVisible(Boolean.TRUE);
        SzolgaltatoVagyokBtn.setVisible(Boolean.TRUE);
        VendegPanel.setVisible(Boolean.FALSE);
        SzolgaltatoPanel.setVisible(Boolean.FALSE);
        this.FoglalasPanel.setVisible(Boolean.FALSE);
        this.AdatokPanel.setVisible(Boolean.FALSE);
            
        
        this.resztVeszRbtn.setSelected(Boolean.TRUE);
        this.resztVeszRbtn1.setSelected(Boolean.TRUE);
        
        for(STATUSZ f : STATUSZ.values()){
            this.vendegList.addItem(f.getStatusz());
        }
        this.vendegek = Form.loadResztvevok();
        this.szolgaltatok = Form.loadSzolgaltatok();
        this.szekek = Form.loadSzekek();
        this.addok();
        
        this.szekSzinezes();
        this.eddigiVendegekListFrissit();
        this.eddigiSzolgaltatokListFrissit();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SzolgaltatoVagyokBtn = new javax.swing.JButton();
        VendegPanel = new javax.swing.JPanel();
        keszBtn = new javax.swing.JButton();
        nevField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        telefonszamField = new javax.swing.JTextField();
        nevLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        telefonszamLbl = new javax.swing.JLabel();
        statuszLbl = new javax.swing.JLabel();
        vendegList = new javax.swing.JComboBox<>();
        resztVeszRbtn = new javax.swing.JRadioButton();
        nemResztVeszRbtn = new javax.swing.JRadioButton();
        modositasBtn = new javax.swing.JButton();
        torlesBtn = new javax.swing.JButton();
        eddigiVendegekList = new javax.swing.JComboBox<>();
        SzolgaltatoPanel = new javax.swing.JPanel();
        keszBtn1 = new javax.swing.JButton();
        nevField1 = new javax.swing.JTextField();
        emailField1 = new javax.swing.JTextField();
        telefonszamField1 = new javax.swing.JTextField();
        nevLbl1 = new javax.swing.JLabel();
        emailLbl1 = new javax.swing.JLabel();
        telefonszamLbl1 = new javax.swing.JLabel();
        árLbl1 = new javax.swing.JLabel();
        szolgaltatasField1 = new javax.swing.JTextField();
        szolgaltatasLbl1 = new javax.swing.JLabel();
        arField1 = new javax.swing.JTextField();
        nemResztVeszRbtn1 = new javax.swing.JRadioButton();
        resztVeszRbtn1 = new javax.swing.JRadioButton();
        torlesBtn1 = new javax.swing.JButton();
        modositasBtn1 = new javax.swing.JButton();
        eddigiSzolgaltatokList = new javax.swing.JComboBox<>();
        VendegVagyokBtn = new javax.swing.JButton();
        FoglalasPanel = new javax.swing.JPanel();
        asztalLbl = new javax.swing.JLabel();
        balSzek0 = new javax.swing.JLabel();
        balSzek1 = new javax.swing.JLabel();
        balSzek2 = new javax.swing.JLabel();
        balSzek3 = new javax.swing.JLabel();
        balSzek4 = new javax.swing.JLabel();
        jobbSzek5 = new javax.swing.JLabel();
        jobbSzek6 = new javax.swing.JLabel();
        jobbSzek7 = new javax.swing.JLabel();
        jobbSzek8 = new javax.swing.JLabel();
        jobbSzek9 = new javax.swing.JLabel();
        AdatokPanel = new javax.swing.JPanel();
        adatokLbl = new javax.swing.JLabel();
        szekAdatokLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        SzolgaltatoVagyokBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        SzolgaltatoVagyokBtn.setForeground(new java.awt.Color(156, 112, 112));
        SzolgaltatoVagyokBtn.setText("Szolgáltató vagyok");
        SzolgaltatoVagyokBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SzolgaltatoVagyokBtnMouseClicked(evt);
            }
        });
        SzolgaltatoVagyokBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SzolgaltatoVagyokBtnActionPerformed(evt);
            }
        });

        keszBtn.setText("Kész");
        keszBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keszBtnMouseClicked(evt);
            }
        });

        nevField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nevField.setForeground(new java.awt.Color(204, 204, 204));
        nevField.setText("Próba Béla");
        nevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevFieldActionPerformed(evt);
            }
        });

        emailField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailField.setForeground(new java.awt.Color(204, 204, 204));
        emailField.setText("probabela12@gmail.com");
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        telefonszamField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        telefonszamField.setForeground(new java.awt.Color(204, 204, 204));
        telefonszamField.setText("06204545457");
        telefonszamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonszamFieldActionPerformed(evt);
            }
        });

        nevLbl.setText("Név:");

        emailLbl.setText("E-mail cím:");

        telefonszamLbl.setText("Telefonszám:");

        statuszLbl.setText("Kinek a meghívottja vagy?");

        resztVeszRbtn.setText("Részt veszek");
        resztVeszRbtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                resztVeszRbtnStateChanged(evt);
            }
        });
        resztVeszRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resztVeszRbtnActionPerformed(evt);
            }
        });

        nemResztVeszRbtn.setText("Nem tudok eljönni");
        nemResztVeszRbtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nemResztVeszRbtnStateChanged(evt);
            }
        });

        modositasBtn.setText("Módosítás");
        modositasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modositasBtnMouseClicked(evt);
            }
        });
        modositasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositasBtnActionPerformed(evt);
            }
        });

        torlesBtn.setText("Törlés");
        torlesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                torlesBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VendegPanelLayout = new javax.swing.GroupLayout(VendegPanel);
        VendegPanel.setLayout(VendegPanelLayout);
        VendegPanelLayout.setHorizontalGroup(
            VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendegPanelLayout.createSequentialGroup()
                .addGroup(VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendegPanelLayout.createSequentialGroup()
                        .addComponent(resztVeszRbtn)
                        .addGap(50, 50, 50)
                        .addComponent(nemResztVeszRbtn))
                    .addGroup(VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(statuszLbl)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendegPanelLayout.createSequentialGroup()
                            .addContainerGap(98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vendegList, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(telefonszamLbl)
                    .addGroup(VendegPanelLayout.createSequentialGroup()
                        .addGroup(VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nevLbl)
                            .addGroup(VendegPanelLayout.createSequentialGroup()
                                .addComponent(emailLbl)
                                .addGap(31, 31, 31)
                                .addGroup(VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nevField, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telefonszamField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(71, 71, 71)
                        .addComponent(keszBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendegPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(eddigiVendegekList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modositasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(torlesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
        VendegPanelLayout.setVerticalGroup(
            VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendegPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nevLbl)
                .addGroup(VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendegPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(emailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(keszBtn)
                        .addGap(30, 30, 30)
                        .addComponent(telefonszamLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(VendegPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(telefonszamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addComponent(statuszLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vendegList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resztVeszRbtn)
                    .addComponent(nemResztVeszRbtn))
                .addGap(18, 18, 18)
                .addGroup(VendegPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modositasBtn)
                    .addComponent(eddigiVendegekList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(torlesBtn)
                .addGap(24, 24, 24))
        );

        keszBtn1.setText("Kész");
        keszBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keszBtn1MouseClicked(evt);
            }
        });

        nevField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nevField1.setForeground(new java.awt.Color(204, 204, 204));
        nevField1.setText("Próba Béla");
        nevField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nevField1ActionPerformed(evt);
            }
        });

        emailField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailField1.setForeground(new java.awt.Color(204, 204, 204));
        emailField1.setText("probabela12@gmail.com");
        emailField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailField1ActionPerformed(evt);
            }
        });

        telefonszamField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        telefonszamField1.setForeground(new java.awt.Color(204, 204, 204));
        telefonszamField1.setText("06204545457");
        telefonszamField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonszamField1ActionPerformed(evt);
            }
        });

        nevLbl1.setText("Név:");

        emailLbl1.setText("E-mail cím:");

        telefonszamLbl1.setText("Telefonszám:");

        árLbl1.setText("Ár:");

        szolgaltatasField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        szolgaltatasField1.setForeground(new java.awt.Color(204, 204, 204));
        szolgaltatasField1.setText("fotós");
        szolgaltatasField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szolgaltatasField1ActionPerformed(evt);
            }
        });

        szolgaltatasLbl1.setText("Szolgáltatás megnevezése:");

        arField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        arField1.setForeground(new java.awt.Color(204, 204, 204));
        arField1.setText("120000");
        arField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arField1ActionPerformed(evt);
            }
        });

        nemResztVeszRbtn1.setText("Nem tudok eljönni");
        nemResztVeszRbtn1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nemResztVeszRbtn1StateChanged(evt);
            }
        });

        resztVeszRbtn1.setText("Részt veszek ");
        resztVeszRbtn1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                resztVeszRbtn1StateChanged(evt);
            }
        });
        resztVeszRbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resztVeszRbtn1ActionPerformed(evt);
            }
        });

        torlesBtn1.setText("Törlés");
        torlesBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                torlesBtn1MouseClicked(evt);
            }
        });

        modositasBtn1.setText("Módosítás");
        modositasBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modositasBtn1MouseClicked(evt);
            }
        });
        modositasBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modositasBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SzolgaltatoPanelLayout = new javax.swing.GroupLayout(SzolgaltatoPanel);
        SzolgaltatoPanel.setLayout(SzolgaltatoPanelLayout);
        SzolgaltatoPanelLayout.setHorizontalGroup(
            SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SzolgaltatoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(szolgaltatasLbl1)
                    .addComponent(árLbl1)
                    .addComponent(telefonszamLbl1)
                    .addGroup(SzolgaltatoPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLbl1)
                            .addComponent(nevLbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nevField1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonszamField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SzolgaltatoPanelLayout.createSequentialGroup()
                                .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(szolgaltatasField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(97, 97, 97)
                                .addComponent(keszBtn1))
                            .addComponent(arField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(SzolgaltatoPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(resztVeszRbtn1)
                .addGap(50, 50, 50)
                .addComponent(nemResztVeszRbtn1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SzolgaltatoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eddigiSzolgaltatokList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modositasBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(torlesBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        SzolgaltatoPanelLayout.setVerticalGroup(
            SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SzolgaltatoPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SzolgaltatoPanelLayout.createSequentialGroup()
                        .addComponent(nevField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SzolgaltatoPanelLayout.createSequentialGroup()
                        .addComponent(nevLbl1)
                        .addGap(65, 65, 65)
                        .addComponent(emailLbl1)
                        .addGap(17, 17, 17)))
                .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keszBtn1))
                .addGap(30, 30, 30)
                .addComponent(telefonszamLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonszamField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(szolgaltatasLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(szolgaltatasField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(árLbl1)
                .addGap(18, 18, 18)
                .addComponent(arField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resztVeszRbtn1)
                    .addComponent(nemResztVeszRbtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SzolgaltatoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modositasBtn1)
                    .addComponent(eddigiSzolgaltatokList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(torlesBtn1)
                .addGap(9, 9, 9))
        );

        VendegVagyokBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VendegVagyokBtn.setForeground(new java.awt.Color(34, 107, 133));
        VendegVagyokBtn.setText("Vendég vagyok");
        VendegVagyokBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VendegVagyokBtnMouseClicked(evt);
            }
        });
        VendegVagyokBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendegVagyokBtnActionPerformed(evt);
            }
        });

        FoglalasPanel.setBackground(new java.awt.Color(255, 255, 255));

        asztalLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/asztal.png"))); // NOI18N

        balSzek0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeBalSzek.png"))); // NOI18N
        balSzek0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balSzek0MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balSzek0MouseEntered(evt);
            }
        });

        balSzek1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeBalSzek.png"))); // NOI18N
        balSzek1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balSzek1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balSzek1MouseEntered(evt);
            }
        });

        balSzek2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeBalSzek.png"))); // NOI18N
        balSzek2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balSzek2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balSzek2MouseEntered(evt);
            }
        });

        balSzek3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeBalSzek.png"))); // NOI18N
        balSzek3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balSzek3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balSzek3MouseEntered(evt);
            }
        });

        balSzek4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeBalSzek.png"))); // NOI18N
        balSzek4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balSzek4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                balSzek4MouseEntered(evt);
            }
        });

        jobbSzek5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeJobbSzek.png"))); // NOI18N
        jobbSzek5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobbSzek5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jobbSzek5MouseEntered(evt);
            }
        });

        jobbSzek6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeJobbSzek.png"))); // NOI18N
        jobbSzek6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobbSzek6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jobbSzek6MouseEntered(evt);
            }
        });

        jobbSzek7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeJobbSzek.png"))); // NOI18N
        jobbSzek7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobbSzek7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jobbSzek7MouseEntered(evt);
            }
        });

        jobbSzek8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeJobbSzek.png"))); // NOI18N
        jobbSzek8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobbSzek8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jobbSzek8MouseEntered(evt);
            }
        });

        jobbSzek9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikonok/feketeJobbSzek.png"))); // NOI18N
        jobbSzek9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jobbSzek9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jobbSzek9MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout FoglalasPanelLayout = new javax.swing.GroupLayout(FoglalasPanel);
        FoglalasPanel.setLayout(FoglalasPanelLayout);
        FoglalasPanelLayout.setHorizontalGroup(
            FoglalasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoglalasPanelLayout.createSequentialGroup()
                .addGroup(FoglalasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FoglalasPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(FoglalasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(balSzek0)
                            .addComponent(balSzek1)))
                    .addGroup(FoglalasPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(balSzek2))
                    .addComponent(balSzek3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(balSzek4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asztalLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FoglalasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jobbSzek5)
                    .addComponent(jobbSzek6)
                    .addComponent(jobbSzek7)
                    .addComponent(jobbSzek8)
                    .addComponent(jobbSzek9))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        FoglalasPanelLayout.setVerticalGroup(
            FoglalasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FoglalasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FoglalasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asztalLbl)
                    .addGroup(FoglalasPanelLayout.createSequentialGroup()
                        .addComponent(balSzek0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balSzek1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balSzek2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balSzek3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balSzek4))
                    .addGroup(FoglalasPanelLayout.createSequentialGroup()
                        .addComponent(jobbSzek5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jobbSzek6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jobbSzek7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jobbSzek8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jobbSzek9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AdatokPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        adatokLbl.setText("Adatok:");

        szekAdatokLbl.setText("Ez a hely még szabad!");

        javax.swing.GroupLayout AdatokPanelLayout = new javax.swing.GroupLayout(AdatokPanel);
        AdatokPanel.setLayout(AdatokPanelLayout);
        AdatokPanelLayout.setHorizontalGroup(
            AdatokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdatokPanelLayout.createSequentialGroup()
                .addGroup(AdatokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdatokPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adatokLbl))
                    .addGroup(AdatokPanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(szekAdatokLbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdatokPanelLayout.setVerticalGroup(
            AdatokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdatokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adatokLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(szekAdatokLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(SzolgaltatoVagyokBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(SzolgaltatoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FoglalasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdatokPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VendegVagyokBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(VendegPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FoglalasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VendegPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SzolgaltatoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SzolgaltatoVagyokBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VendegVagyokBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AdatokPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VendegVagyokBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendegVagyokBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VendegVagyokBtnActionPerformed

    private void SzolgaltatoVagyokBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SzolgaltatoVagyokBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SzolgaltatoVagyokBtnActionPerformed

    private void nevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nevFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void telefonszamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonszamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonszamFieldActionPerformed

    private void VendegVagyokBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VendegVagyokBtnMouseClicked
        VendegVagyokBtn.setVisible(Boolean.FALSE);
        SzolgaltatoVagyokBtn.setVisible(Boolean.FALSE);
        VendegPanel.setVisible(Boolean.TRUE);
        SzolgaltatoPanel.setVisible(Boolean.FALSE);
        this.FoglalasPanel.setVisible(Boolean.TRUE);
        this.AdatokPanel.setVisible(Boolean.TRUE);
        eddigiVendegekListFrissit();
    }//GEN-LAST:event_VendegVagyokBtnMouseClicked

    private void nevField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nevField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nevField1ActionPerformed

    private void emailField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailField1ActionPerformed

    private void telefonszamField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonszamField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonszamField1ActionPerformed

    private void szolgaltatasField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szolgaltatasField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_szolgaltatasField1ActionPerformed

    private void arField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arField1ActionPerformed

    private void SzolgaltatoVagyokBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SzolgaltatoVagyokBtnMouseClicked
        VendegVagyokBtn.setVisible(Boolean.FALSE);
        SzolgaltatoVagyokBtn.setVisible(Boolean.FALSE);
        VendegPanel.setVisible(Boolean.FALSE);
        SzolgaltatoPanel.setVisible(Boolean.TRUE);
        this.FoglalasPanel.setVisible(Boolean.TRUE);
        this.AdatokPanel.setVisible(Boolean.TRUE);
    }//GEN-LAST:event_SzolgaltatoVagyokBtnMouseClicked

    private void resztVeszRbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resztVeszRbtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resztVeszRbtn1ActionPerformed

    private void resztVeszRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resztVeszRbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resztVeszRbtnActionPerformed

    private void resztVeszRbtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_resztVeszRbtnStateChanged
       if(this.resztVeszRbtn.isSelected()){
           this.nemResztVeszRbtn.setSelected(Boolean.FALSE);
       }
       if(this.resztVeszRbtn.isSelected() == Boolean.FALSE){
           this.nemResztVeszRbtn.setSelected(Boolean.TRUE);
       }
    }//GEN-LAST:event_resztVeszRbtnStateChanged

    private void nemResztVeszRbtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nemResztVeszRbtnStateChanged
       if(this.nemResztVeszRbtn.isSelected()){
            this.resztVeszRbtn.setSelected(Boolean.FALSE);
        }
        if(this.nemResztVeszRbtn.isSelected() == Boolean.FALSE){
            this.resztVeszRbtn.setSelected(Boolean.TRUE);
        }
    }//GEN-LAST:event_nemResztVeszRbtnStateChanged

    private void resztVeszRbtn1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_resztVeszRbtn1StateChanged
        if(this.resztVeszRbtn1.isSelected()){
           this.nemResztVeszRbtn1.setSelected(Boolean.FALSE);
       }
       if(this.resztVeszRbtn1.isSelected() == Boolean.FALSE){
           this.nemResztVeszRbtn1.setSelected(Boolean.TRUE);
       }
    }//GEN-LAST:event_resztVeszRbtn1StateChanged

    private void nemResztVeszRbtn1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nemResztVeszRbtn1StateChanged
       if(this.nemResztVeszRbtn1.isSelected()){
            this.resztVeszRbtn1.setSelected(Boolean.FALSE);
        }
        if(this.nemResztVeszRbtn1.isSelected() == Boolean.FALSE){
            this.resztVeszRbtn1.setSelected(Boolean.TRUE);
        }
    }//GEN-LAST:event_nemResztVeszRbtn1StateChanged

    private void keszBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keszBtnMouseClicked
        String nev= this.nevField.getText();
        if(nev.length() < 1){
            JOptionPane.showMessageDialog(rootPane, "Kérem, írja be a nevét!");
        }
        else{
            String email = this.emailField.getText();
            String telefonszam = this.telefonszamField.getText();
            Boolean resztVesz = this.resztVeszRbtn.isSelected();
            STATUSZ statusz = STATUSZ.VOLEGENYKOZELI;
            String statuszStr = this.vendegList.getSelectedItem().toString();
            
            
            for(STATUSZ f : STATUSZ.values()){
                if(f.name().equals(statuszStr)){
                    statusz = f;
                    break;
                }
            }
            
            Resztvevo vendeg = new Resztvevo(statusz, nev, email, telefonszam, resztVesz, szekSzam);
            
            Funkciok<Resztvevo> v = new Funkciok<>();
            v.mentes(vendeg);
            this.vendegek.add(vendeg);
            
            szekek.get(szekSzam).szekFoglalas();
            osszesSzekMentese();
            
            szekSzam = -1;
            
            this.nevField.setText("");
            this.emailField.setText("");
            this.telefonszamField.setText("");
            this.resztVeszRbtn.setSelected(Boolean.TRUE);
            this.vendegList.setSelectedIndex(0);
            this.VendegPanel.setVisible(Boolean.FALSE);
            
            szekSzinezes();
            eddigiVendegekListFrissit();
            
            FoglalasPanel.setVisible(Boolean.FALSE);
            AdatokPanel.setVisible(Boolean.FALSE);
            VendegVagyokBtn.setVisible(Boolean.TRUE);
            SzolgaltatoVagyokBtn.setVisible(Boolean.TRUE);
        }
    }//GEN-LAST:event_keszBtnMouseClicked

    private void keszBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keszBtn1MouseClicked
       String nev= this.nevField1.getText();
        if(nev.length() < 1 ||  szekSzam < 0){
            JOptionPane.showMessageDialog(rootPane, "Hibás kitöltés, a név mező kitöltése és szék foglalás kötelező!");
        }
        else{
            String email = this.emailField1.getText();
            String telefonszam = this.telefonszamField1.getText();
            String szolgaltatas = this.szolgaltatasField1.getText();
            Boolean resztVesz = this.resztVeszRbtn1.isSelected();
            Integer ar = Integer.parseInt(this.arField1.getText());
            
            
            Szolgaltato szolgaltato = new Szolgaltato(nev, email, telefonszam, resztVesz, ar, szolgaltatas, szekSzam);
            
            Funkciok<Szolgaltato> sz = new Funkciok<>();
            sz.mentes(szolgaltato);
            this.szolgaltatok.add(szolgaltato);
            
            szekek.get(szekSzam).szekFoglalas();
            osszesSzekMentese();
            
            szekSzam = -1;
            
            this.nevField1.setText("");
            this.emailField1.setText("");
            this.telefonszamField1.setText("");
            this.resztVeszRbtn1.setSelected(Boolean.TRUE);
            this.arField1.setText("");
            this.szolgaltatasField1.setText("");
            this.SzolgaltatoPanel.setVisible(Boolean.FALSE);
            
            szekSzinezes();
            eddigiSzolgaltatokListFrissit();
            
            FoglalasPanel.setVisible(Boolean.FALSE);
            AdatokPanel.setVisible(Boolean.FALSE);
            VendegVagyokBtn.setVisible(Boolean.TRUE);
            SzolgaltatoVagyokBtn.setVisible(Boolean.TRUE);
            
        }
    }//GEN-LAST:event_keszBtn1MouseClicked

    private void balSzek0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek0MouseClicked
        szekKijelölés(0);
    }//GEN-LAST:event_balSzek0MouseClicked

    private void balSzek1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek1MouseClicked
        szekKijelölés(1);
    }//GEN-LAST:event_balSzek1MouseClicked

    private void balSzek2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek2MouseClicked
        szekKijelölés(2);
    }//GEN-LAST:event_balSzek2MouseClicked

    private void balSzek3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek3MouseClicked
        szekKijelölés(3);
    }//GEN-LAST:event_balSzek3MouseClicked

    private void balSzek4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek4MouseClicked
        szekKijelölés(4);
    }//GEN-LAST:event_balSzek4MouseClicked

    private void jobbSzek5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek5MouseClicked
        szekKijelölés(5);
    }//GEN-LAST:event_jobbSzek5MouseClicked

    private void jobbSzek6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek6MouseClicked
        szekKijelölés(6);
    }//GEN-LAST:event_jobbSzek6MouseClicked

    private void jobbSzek7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek7MouseClicked
        szekKijelölés(7);
    }//GEN-LAST:event_jobbSzek7MouseClicked

    private void jobbSzek8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek8MouseClicked
        szekKijelölés(8);
    }//GEN-LAST:event_jobbSzek8MouseClicked

    private void jobbSzek9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek9MouseClicked
        szekKijelölés(9);
    }//GEN-LAST:event_jobbSzek9MouseClicked

    private void balSzek0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek0MouseEntered
        adatokKiirasa(0);
    }//GEN-LAST:event_balSzek0MouseEntered

    private void balSzek1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek1MouseEntered
        adatokKiirasa(1);
    }//GEN-LAST:event_balSzek1MouseEntered

    private void balSzek2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek2MouseEntered
        adatokKiirasa(2);
    }//GEN-LAST:event_balSzek2MouseEntered

    private void balSzek3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek3MouseEntered
        adatokKiirasa(3);
    }//GEN-LAST:event_balSzek3MouseEntered

    private void balSzek4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balSzek4MouseEntered
        adatokKiirasa(4);
    }//GEN-LAST:event_balSzek4MouseEntered

    private void jobbSzek5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek5MouseEntered
        adatokKiirasa(5);
    }//GEN-LAST:event_jobbSzek5MouseEntered

    private void jobbSzek6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek6MouseEntered
       adatokKiirasa(6);
    }//GEN-LAST:event_jobbSzek6MouseEntered

    private void jobbSzek7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek7MouseEntered
        adatokKiirasa(7);
    }//GEN-LAST:event_jobbSzek7MouseEntered

    private void jobbSzek8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek8MouseEntered
        adatokKiirasa(8);
    }//GEN-LAST:event_jobbSzek8MouseEntered

    private void jobbSzek9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jobbSzek9MouseEntered
        adatokKiirasa(9);
    }//GEN-LAST:event_jobbSzek9MouseEntered

    private void modositasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositasBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modositasBtnActionPerformed

    private void modositasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modositasBtnMouseClicked
        String aktNev = eddigiVendegekList.getSelectedItem().toString();
        STATUSZ aktStatusz = STATUSZ.valueOf("VOLEGENYKOZELI");
        Integer aktSzekSzam = -1;
        String aktTelefonszam = "0";
        Boolean aktReszVesz = false;
        String aktEmail = "0";
                
        for(int i = 0; i< vendegek.size();i++){
            if(vendegek.get(i).getNev().equals(aktNev)){
                aktStatusz = vendegek.get(i).getStatusz();
                aktSzekSzam = vendegek.get(i).getSzekSzam();
                aktTelefonszam = vendegek.get(i).getTelefonszam();
                aktReszVesz = vendegek.get(i).isResztVesz();
                aktEmail = vendegek.get(i).getEmail();
                break;
            }
        }
        
        nevField.setText(aktNev);
        vendegList.setSelectedItem(aktStatusz);
        telefonszamField.setText(aktTelefonszam);
        resztVeszRbtn.setSelected(aktReszVesz);
        emailField.setText(aktEmail);
        
        //Törlés 
        for(int i=0; i<vendegek.size();i++){
            if(vendegek.get(i).getNev().equals(aktNev)){
                vendegek.remove(i);
                break;
            }
        }
        osszesVendegMentese();
        this.vendegek = Form.loadResztvevok();
        szekek.get(aktSzekSzam).szekFoglalasTorles();
        osszesSzekMentese();
        this.szekek = Form.loadSzekek();
        szekSzinezes();
    }//GEN-LAST:event_modositasBtnMouseClicked

    private void torlesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_torlesBtnMouseClicked
        String nevTorles = this.eddigiVendegekList.getSelectedItem().toString();
        Integer aktSzekSzam = -1;
        for(int i=0; i<vendegek.size();i++){
            if(vendegek.get(i).getNev().equals(nevTorles)){
                aktSzekSzam = vendegek.get(i).getSzekSzam();
                vendegek.remove(i);
                break;
            }
        }
        osszesVendegMentese();
        this.vendegek = Form.loadResztvevok();
        szekek.get(aktSzekSzam).szekFoglalasTorles();
        osszesSzekMentese();
        this.szekek = Form.loadSzekek();
        szekSzinezes();
        
        eddigiVendegekListFrissit();
        
        JOptionPane.showMessageDialog(null, "Sikeres törlés");
        
        VendegVagyokBtn.setVisible(Boolean.TRUE);
        SzolgaltatoVagyokBtn.setVisible(Boolean.TRUE);
        VendegPanel.setVisible(Boolean.FALSE);
        SzolgaltatoPanel.setVisible(Boolean.FALSE);
        this.FoglalasPanel.setVisible(Boolean.FALSE);
        this.AdatokPanel.setVisible(Boolean.FALSE);
        
    }//GEN-LAST:event_torlesBtnMouseClicked

    private void torlesBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_torlesBtn1MouseClicked
        String nevTorles = this.eddigiSzolgaltatokList.getSelectedItem().toString();
        Integer aktSzekSzam = -1;
        for(int i=0; i<szolgaltatok.size();i++){
            if(szolgaltatok.get(i).getNev().equals(nevTorles)){
                aktSzekSzam = szolgaltatok.get(i).getSzekSzam();
                szolgaltatok.remove(i);
                break;
            }
        }
        osszesSzolgaltatoMentese();
        this.szolgaltatok = Form.loadSzolgaltatok();
        szekek.get(aktSzekSzam).szekFoglalasTorles();
        osszesSzekMentese();
        this.szekek = Form.loadSzekek();
        szekSzinezes();
        
        eddigiSzolgaltatokListFrissit();
        
        JOptionPane.showMessageDialog(null, "Sikeres törlés");
        
        VendegVagyokBtn.setVisible(Boolean.TRUE);
        SzolgaltatoVagyokBtn.setVisible(Boolean.TRUE);
        VendegPanel.setVisible(Boolean.FALSE);
        SzolgaltatoPanel.setVisible(Boolean.FALSE);
        this.FoglalasPanel.setVisible(Boolean.FALSE);
        this.AdatokPanel.setVisible(Boolean.FALSE);
        
    }//GEN-LAST:event_torlesBtn1MouseClicked

    private void modositasBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modositasBtn1MouseClicked
        String aktNev = eddigiSzolgaltatokList.getSelectedItem().toString();
        Integer aktAr = 0;
        String aktSzolgaltatas = "";
        Integer aktSzekSzam = -1;
        String aktTelefonszam = "0";
        Boolean aktReszVesz = false;
        String aktEmail = "0";
                
        for(int i = 0; i< szolgaltatok.size();i++){
            if(szolgaltatok.get(i).getNev().equals(aktNev)){
                aktAr = szolgaltatok.get(i).getAr();
                aktSzolgaltatas = szolgaltatok.get(i).getSzolgaltatas();
                aktSzekSzam = szolgaltatok.get(i).getSzekSzam();
                aktTelefonszam = szolgaltatok.get(i).getTelefonszam();
                aktReszVesz = szolgaltatok.get(i).isResztVesz();
                aktEmail = szolgaltatok.get(i).getEmail();
                break;
            }
        }
        
        arField1.setText(Integer.toString(aktAr));
        szolgaltatasField1.setText(aktSzolgaltatas);
        nevField1.setText(aktNev);
        telefonszamField1.setText(aktTelefonszam);
        resztVeszRbtn1.setSelected(aktReszVesz);
        emailField1.setText(aktEmail);
        
        //Törlés 
        for(int i=0; i<szolgaltatok.size();i++){
            if(szolgaltatok.get(i).getNev().equals(aktNev)){
                szolgaltatok.remove(i);
                break;
            }
        }
        osszesSzolgaltatoMentese();
        this.szolgaltatok = Form.loadSzolgaltatok();
        szekek.get(aktSzekSzam).szekFoglalasTorles();
        osszesSzekMentese();
        this.szekek = Form.loadSzekek();
        szekSzinezes();
    }//GEN-LAST:event_modositasBtn1MouseClicked

    private void modositasBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modositasBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modositasBtn1ActionPerformed
    private void eddigiVendegekListFrissit(){
        this.eddigiVendegekList.removeAllItems();
        for(int i = 0; i<vendegek.size(); i++){
            String nev = vendegek.get(i).getNev();
            this.eddigiVendegekList.addItem(nev);
        }
    }
    
    private void eddigiSzolgaltatokListFrissit(){
        this.eddigiSzolgaltatokList.removeAllItems();
        for(int i = 0; i<szolgaltatok.size(); i++){
            String nev = szolgaltatok.get(i).getNev();
            this.eddigiSzolgaltatokList.addItem(nev);
        }
    }
    
    private void adatokKiirasa(Integer lblSzam){
        if(szekek.get(lblSzam).isFoglalt()){
            for(int i = 0; i < vendegek.size(); i++){
                if(vendegek.get(i).getSzekSzam() == lblSzam){
                    szekAdatokLbl.setText("Név: " + vendegek.get(i).getNev() +
                                            "\n (" + vendegek.get(i).getStatusz().getStatusz() +")");
                    break;
                }
                else if(szolgaltatok.get(i).getSzekSzam() == lblSzam){
                    szekAdatokLbl.setText("Név: " + szolgaltatok.get(i).getNev() +
                                            "\n (" + szolgaltatok.get(i).getSzolgaltatas()+")");
                    break;
                }
            }
        }
        else{
            szekAdatokLbl.setText("Ez a hely még szabad!");
        }
    }
    private void szekKijelölés(Integer lblSzam){
        if(lblSzam<5){
            if(szekek.get(lblSzam).isFoglalt() == Boolean.FALSE){
                szekSzinezes();
                ImageIcon icon = new ImageIcon("C:\\Users\\solya\\OneDrive\\Dokumentumok\\NetBeansProjects\\ultetes\\src\\ikonok\\sargaBalSzek.png");
                labelek.get(lblSzam).setIcon(icon);
                szekSzam = lblSzam;
            }
        }
        else if(lblSzam>4){
            if(szekek.get(lblSzam).isFoglalt() == Boolean.FALSE){
                szekSzinezes();
                ImageIcon icon = new ImageIcon("C:\\Users\\solya\\OneDrive\\Dokumentumok\\NetBeansProjects\\ultetes\\src\\ikonok\\sargaJobbSzek.png");
                labelek.get(lblSzam).setIcon(icon);
                szekSzam = lblSzam;
            }
        }
    }
    private void szekSzinezes(){
        for(int i = 0; i<szekek.size();i++){
            szekek.get(i).setSzekNeve(labelek.get(i));            
        }
        //szekek.get(0).setSzekNeve(balSzek0);
        //szekek.get(0).getSzekNeve().setIcon(icon1);
        for(int i = 0; i < 10; i++){
            if(szekek.get(i).isFoglalt()){
                if(i<5){
                    ImageIcon icon1 = new ImageIcon("C:\\Users\\solya\\OneDrive\\Dokumentumok\\NetBeansProjects\\ultetes\\src\\ikonok\\pirosBalSzek.png");
                    szekek.get(i).getSzekNeve().setIcon(icon1);
                }
                else if(i>4){
                    ImageIcon icon2 = new ImageIcon("C:\\Users\\solya\\OneDrive\\Dokumentumok\\NetBeansProjects\\ultetes\\src\\ikonok\\pirosJobbSzek.png");
                    szekek.get(i).getSzekNeve().setIcon(icon2);
                }
            }
            else{
                if(i<5){
                    ImageIcon icon3 = new ImageIcon("C:\\Users\\solya\\OneDrive\\Dokumentumok\\NetBeansProjects\\ultetes\\src\\ikonok\\feketeBalSzek.png");
                    szekek.get(i).getSzekNeve().setIcon(icon3);
                }
                else if(i>4){
                    ImageIcon icon4 = new ImageIcon("C:\\Users\\solya\\OneDrive\\Dokumentumok\\NetBeansProjects\\ultetes\\src\\ikonok\\feketeJobbSzek.png");
                    szekek.get(i).getSzekNeve().setIcon(icon4);
                }
            }
        }
    }
    
    
    private static List<Resztvevo> loadResztvevok(){
        List<Resztvevo> vendegek = new ArrayList<>();
        try{
        
            String filename = "Resztvevo.xml";
            File file = new File(filename);
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document xml = builder.parse(file);
            xml.normalize();
            
            NodeList vendegCsomopontok = xml.getElementsByTagName("Resztvevo");
            for(Integer i = 0; i < vendegCsomopontok.getLength(); i++){
                Node vendegCsomopont = vendegCsomopontok.item(i);
                Element vendegAdatai = (Element)vendegCsomopont;
                
                String statuszStr = vendegAdatai.getElementsByTagName("statusz").item(0).getTextContent();
                String szekSzamStr = vendegAdatai.getElementsByTagName("szekSzam").item(0).getTextContent();
                String telefonszam = vendegAdatai.getElementsByTagName("telefonszam").item(0).getTextContent();
                String resztVeszStr = vendegAdatai.getElementsByTagName("resztVesz").item(0).getTextContent();
                String nev = vendegAdatai.getElementsByTagName("nev").item(0).getTextContent();
                String email = vendegAdatai.getElementsByTagName("email").item(0).getTextContent();
                
                Integer szekSzam = Integer.parseInt(szekSzamStr);
                Boolean resztVesz = Boolean.parseBoolean(resztVeszStr);
                STATUSZ statusz = STATUSZ.valueOf(statuszStr);
                                
                Resztvevo r = new Resztvevo(statusz, nev, email, telefonszam, resztVesz, szekSzam);
                vendegek.add(r);
            }
            
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nem sikerült betölteni a vendégek adatait! (" + ex.toString() + ")");
        }
        return vendegek;
    }
    
    private static List<Szolgaltato> loadSzolgaltatok(){
        List<Szolgaltato> szolgaltatok = new ArrayList<>();
        try{
        
            String filename = "Szolgaltato.xml";
            File file = new File(filename);
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document xml = builder.parse(file);
            xml.normalize();
            
            NodeList szolgaltatoCsomopontok = xml.getElementsByTagName("Szolgaltato");
            for(Integer i = 0; i < szolgaltatoCsomopontok.getLength(); i++){
                Node szolgaltatoCsomopont = szolgaltatoCsomopontok.item(i);
                Element szolgaltatoAdatai = (Element)szolgaltatoCsomopont;
                
                String arStr = szolgaltatoAdatai.getElementsByTagName("ar").item(0).getTextContent();
                String szekSzamStr = szolgaltatoAdatai.getElementsByTagName("szekSzam").item(0).getTextContent();
                String telefonszam = szolgaltatoAdatai.getElementsByTagName("telefonszam").item(0).getTextContent();
                String resztVeszStr = szolgaltatoAdatai.getElementsByTagName("resztVesz").item(0).getTextContent();
                String szolgaltatas = szolgaltatoAdatai.getElementsByTagName("szolgaltatas").item(0).getTextContent();
                String nev = szolgaltatoAdatai.getElementsByTagName("nev").item(0).getTextContent();
                String email = szolgaltatoAdatai.getElementsByTagName("email").item(0).getTextContent();
                
                Integer szekSzam = Integer.parseInt(szekSzamStr);
                Integer ar = Integer.parseInt(arStr);
                Boolean resztVesz = Boolean.parseBoolean(resztVeszStr);
                                
                Szolgaltato sz = new Szolgaltato(nev, email, telefonszam, resztVesz, ar, szolgaltatas, szekSzam);
                szolgaltatok.add(sz);
            }
            
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nem sikerült betölteni a szolgáltatók adatait! (" + ex.toString() + ")");
        }
        return szolgaltatok;
    }
    
    private static List<Szek> loadSzekek(){
        List<Szek> szekek = new ArrayList<>();
        try{
        
            String filename = "Szek.xml";
            File file = new File(filename);
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document xml = builder.parse(file);
            xml.normalize();
            
            NodeList szekCsomopontok = xml.getElementsByTagName("Szek");
            for(Integer i = 0; i < szekCsomopontok.getLength(); i++){
                Node szekCsomopont = szekCsomopontok.item(i);
                Element szekAdatai = (Element)szekCsomopont;
                
                String foglaltStr = szekAdatai.getElementsByTagName("foglalt").item(0).getTextContent();
                String szekSzamStr = szekAdatai.getElementsByTagName("szekSzam").item(0).getTextContent();                
                String szekNeveStr = szekAdatai.getElementsByTagName("szekNeve").item(0).getTextContent();
                
                Integer szekSzam = Integer.parseInt(szekSzamStr);
                Boolean foglalt = Boolean.parseBoolean(foglaltStr);
                JLabel szekNeve = new JLabel(szekNeveStr);
                                
                Szek sz = new Szek(foglalt,szekSzam,szekNeve);
                szekek.add(sz);
            }
            
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nem sikerült betölteni a székek adatait! (" + ex.toString() + ")");
        }
        return szekek;
    }
    
    private void addok(){
        labelek.add(balSzek0);
        labelek.add(balSzek1);
        labelek.add(balSzek2);
        labelek.add(balSzek3);
        labelek.add(balSzek4);
        
        labelek.add(jobbSzek5);
        labelek.add(jobbSzek6);
        labelek.add(jobbSzek7);
        labelek.add(jobbSzek8);
        labelek.add(jobbSzek9);
    }
    
    private void osszesSzekMentese(){
        osszesMentes("Szek.xml");
        for(int i = 0; i< szekek.size();i++){
           try{
            Funkciok<Szek> sz2 = new Funkciok<>();
            sz2.mentes(szekek.get(i));
           } 
           catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Hiba történt a mentés során: " + ex.toString());
           }
           
        }
    }
    private void osszesVendegMentese(){
        osszesMentes("Resztvevo.xml");
        for(int i = 0; i< vendegek.size();i++){
           try{
            Funkciok<Resztvevo> r2 = new Funkciok<>();
            r2.mentes(vendegek.get(i));
           } 
           catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Hiba történt a mentés során: " + ex.toString());
           }
           
        }
    }
    
    private void osszesSzolgaltatoMentese(){
        osszesMentes("Szolgaltato.xml");
        for(int i = 0; i< szolgaltatok.size();i++){
           try{
            Funkciok<Szolgaltato> sz2 = new Funkciok<>();
            sz2.mentes(szolgaltatok.get(i));
           } 
           catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Hiba történt a mentés során: " + ex.toString());
           }
           
        }
    }
    public static void osszesMentes(String filename){
        try{
            String filename1 = filename;
            File file = new File(filename1);
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            Document xml = builder.parse(file);
            xml.normalize();
            
            TransformerFactory tf = TransformerFactory.newInstance();
            Transformer transformer = tf.newTransformer();
            
            
            Node elso = xml.getFirstChild();
            removeChilds(elso);
            DOMSource source = new DOMSource(xml);
            StreamResult result = new StreamResult(file);
            transformer.transform(source, result);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Hiba történt a mentés során: " + ex.toString());
            
        }
    }
    public static void removeChilds(Node node) {
        while (node.hasChildNodes())
            node.removeChild(node.getFirstChild());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdatokPanel;
    private javax.swing.JPanel FoglalasPanel;
    private javax.swing.JPanel SzolgaltatoPanel;
    private javax.swing.JButton SzolgaltatoVagyokBtn;
    private javax.swing.JPanel VendegPanel;
    private javax.swing.JButton VendegVagyokBtn;
    private javax.swing.JLabel adatokLbl;
    private javax.swing.JTextField arField1;
    private javax.swing.JLabel asztalLbl;
    private javax.swing.JLabel balSzek0;
    private javax.swing.JLabel balSzek1;
    private javax.swing.JLabel balSzek2;
    private javax.swing.JLabel balSzek3;
    private javax.swing.JLabel balSzek4;
    private javax.swing.JComboBox<String> eddigiSzolgaltatokList;
    private javax.swing.JComboBox<String> eddigiVendegekList;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailField1;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JLabel emailLbl1;
    private javax.swing.JLabel jobbSzek5;
    private javax.swing.JLabel jobbSzek6;
    private javax.swing.JLabel jobbSzek7;
    private javax.swing.JLabel jobbSzek8;
    private javax.swing.JLabel jobbSzek9;
    private javax.swing.JButton keszBtn;
    private javax.swing.JButton keszBtn1;
    private javax.swing.JButton modositasBtn;
    private javax.swing.JButton modositasBtn1;
    private javax.swing.JRadioButton nemResztVeszRbtn;
    private javax.swing.JRadioButton nemResztVeszRbtn1;
    private javax.swing.JTextField nevField;
    private javax.swing.JTextField nevField1;
    private javax.swing.JLabel nevLbl;
    private javax.swing.JLabel nevLbl1;
    private javax.swing.JRadioButton resztVeszRbtn;
    private javax.swing.JRadioButton resztVeszRbtn1;
    private javax.swing.JLabel statuszLbl;
    private javax.swing.JLabel szekAdatokLbl;
    private javax.swing.JTextField szolgaltatasField1;
    private javax.swing.JLabel szolgaltatasLbl1;
    private javax.swing.JTextField telefonszamField;
    private javax.swing.JTextField telefonszamField1;
    private javax.swing.JLabel telefonszamLbl;
    private javax.swing.JLabel telefonszamLbl1;
    private javax.swing.JButton torlesBtn;
    private javax.swing.JButton torlesBtn1;
    private javax.swing.JComboBox<String> vendegList;
    private javax.swing.JLabel árLbl1;
    // End of variables declaration//GEN-END:variables
}
